# Data parameters
# SPADE parameters
# PSF parameters
# Number of surrogates
n_surr : 100
# Significance level
alpha : 0.05
# Spectrum
spectra : ['3d#']
# PSR parameters
psr_param : [0,0,0]
# Statistical correction
correction : 'bonf'
# Minimum number of occurrences
min_occ : 4
