# Data parameters
# SPADE parameters
# PSF parameters
# Number of surrogates
n_surr : 1000
# Significance level
alpha : 0.05
# Spectrum
spectra : ['3d#']
# PSR parameters
# psr_param : [0,0,0]
psr_param : null
# Statistical correction
correction : 'bonferroni'
# Minimum number of occurrences
min_occ : 10 
